apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: na5r17xyz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: na5r17xyz-go 
  name: na5r17xyz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: na5r17xyz-go 
